/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'r3pc' at '17/02/20 12:39' with Gradle 2.9
 *
 * @author r3pc, @date 17/02/20 12:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
